### ISSUE TITLE
Date strings not formatted correctly on build

### ISSUE THREAD

**Issue by loffa** [insektionen/songlist#17]
The strings for `updated` values in the JSON and XML files are not formatted correctly at all times when running the build script.

The issue is probably due to the script using locale from the build environment (specifically if run inside docker etc.) to format the dates. It should be statically set to a specified format like ISO8601 or RFC3339.

**Comment by StelFoog** [comment]
Issue occurs here https://github.com/insektionen/songlist/blob/5783d46eedc032cbf3627b928a049ed5c6d702f9/src/scripts/build.ts#L19

**Comment by Cactooz** [comment]
The format is already stated as ISO 8601 in the README.md so we should continue to use that.
